on:
  push:
    tags:
      - 'v*'
name: Release
jobs:
  release:
    name: Release with goreleaser
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: goreleaser
      uses: docker://goreleaser/goreleaser
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: release
      if: success()
